import React, { useState } from 'react';

const ChevronDownIcon = () => (
    // FIX: Corrected the malformed viewBox attribute from `0 0 24" 24"` to `0 0 24 24`.
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-5 w-5 transition-transform duration-300"><polyline points="6 9 12 15 18 9"></polyline></svg>
);

const CopyIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
);

const CheckIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><polyline points="20 6 9 17 4 12"></polyline></svg>
);


const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="border-b border-border-color">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="w-full flex justify-between items-center py-4 text-left font-semibold text-lg text-primary"
            >
                <span>{title}</span>
                <span className={`${isOpen ? 'rotate-180' : ''}`}><ChevronDownIcon /></span>
            </button>
            <div className={`overflow-hidden transition-all duration-500 ${isOpen ? 'max-h-[2000px]' : 'max-h-0'}`}>
                <div className="pb-4 prose max-w-none prose-p:text-text-secondary prose-headings:text-primary prose-strong:text-text-primary prose-a:text-primary hover:prose-a:underline prose-li:text-text-secondary">
                    {children}
                </div>
            </div>
        </div>
    );
}

const CodeBlock: React.FC<{ children: string }> = ({ children }) => {
    const [copied, setCopied] = useState(false);
    
    const handleCopy = () => {
        navigator.clipboard.writeText(children);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="relative">
            <button onClick={handleCopy} className="absolute top-2 right-2 p-1.5 rounded-md bg-white/10 hover:bg-white/20 text-white transition-colors duration-200">
                {copied ? <CheckIcon /> : <CopyIcon />}
            </button>
            <pre className="bg-gray-800 dark:bg-black/50 text-white p-4 rounded-md overflow-x-auto text-sm font-mono">
                <code>{children}</code>
            </pre>
        </div>
    );
};

const supabaseSetupScript = `-- 1. Create the 'courses' table
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT,
  price NUMERIC,
  "imageUrl" TEXT,
  duration TEXT,
  paddle_product_id TEXT
);

-- 2. Disable Row Level Security (RLS) for easy development.
-- NOTE: You should enable and configure RLS policies before going to production.
ALTER TABLE public.courses DISABLE ROW LEVEL SECURITY;

-- 3. Insert mock data to populate the courses section
INSERT INTO public.courses (title, description, type, price, "imageUrl", duration, paddle_product_id)
VALUES
  ('Foundations of Mindfulness', 'A comprehensive video series teaching the core principles of mindfulness to reduce stress and cultivate presence.', 'Video Course', 49.99, 'https://picsum.photos/400/300?random=10', '4 Hours', 'prod_12345'),
  ('Morning Gratitude Meditation', 'Begin each day with a positive and grateful mindset through this beautifully guided audio meditation.', 'Audio Meditation', 9.99, 'https://picsum.photos/400/300?random=11', '15 Mins', 'prod_12346'),
  ('Chakra Balancing for Beginners', 'An introductory video course to understanding, clearing, and balancing your seven chakras for spiritual well-being.', 'Video Course', 69.99, 'https://picsum.photos/400/300?random=12', '6 Hours', 'prod_12347'),
  ('Deep Sleep Hypnosis', 'A soothing audio journey designed to help you release the day and drift into a deep, restorative, and peaceful sleep.', 'Audio Meditation', 14.99, 'https://picsum.photos/400/300?random=13', '30 Mins', 'prod_12348');

-- 4. Create the 'appointments' table
CREATE TABLE public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL
);

-- 5. Disable RLS for the appointments table
ALTER TABLE public.appointments DISABLE ROW LEVEL SECURITY;
`

const supabaseClientScript = `import { createClient } from '@supabase/supabase-js'

// IMPORTANT: Use environment variables for these.
// See the Deployment section for how to set these up.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
`

const paddleEffectScript = `import React, { useEffect } from 'react';

// In your main App.tsx or a layout component
useEffect(() => {
  // Ensure the Paddle script has loaded
  if ((window as any).Paddle) {
    (window as any).Paddle.Setup({ vendor: import.meta.env.VITE_PADDLE_VENDOR_ID });
  }
}, []);`

const paddleCheckoutScript = `const handleBuyNow = (paddleId) => {
  if ((window as any).Paddle) {
    (window as any).Paddle.Checkout.open({
      product: paddleId,
      // You can also pass customer email, etc.
      // email: 'customer@example.com',
    });
  }
};`

const BackendGuide: React.FC = () => {
    return (
        <section id="backend-guide" className="py-20 bg-background">
            <div className="container mx-auto px-6">
                <div className="text-center mb-16">
                    <h2 className="text-4xl font-serif font-bold text-primary">Developer Guide</h2>
                    <p className="text-lg text-text-secondary mt-2 max-w-2xl mx-auto">How to connect the backend, payments, and deploy this site.</p>
                </div>
                <div className="max-w-4xl mx-auto bg-card-background p-8 rounded-xl shadow-elegant">
                    <Section title="Quick Start: Prerequisites">
                        <p>Before you begin, make sure you have the following installed:</p>
                        <ul>
                            <li><strong>Node.js and npm:</strong> Required to run the project and install packages.</li>
                            <li><strong>A code editor:</strong> Such as VS Code.</li>
                            <li><strong>Git:</strong> For version control and deployment.</li>
                        </ul>
                    </Section>

                    <Section title="1. Backend Setup with Supabase">
                        <p>Supabase is an open-source Firebase alternative providing a PostgreSQL database, authentication, and auto-generated APIs.</p>
                        
                        <h4>Step 1: Create a Supabase Project</h4>
                        <ol>
                            <li>Go to <a href="https://supabase.com" target="_blank" rel="noopener noreferrer">supabase.com</a> and sign up/log in.</li>
                            <li>Create a new project. Choose a strong database password and save it securely.</li>
                        </ol>

                        <h4>Step 2: Run the Database Setup Script</h4>
                        <p>Navigate to the **SQL Editor** in your Supabase dashboard. Click "+ New query" and paste the entire script below. This will create your `courses` and `appointments` tables and add the sample course data in one step.</p>
                        <CodeBlock>{supabaseSetupScript}</CodeBlock>

                        <h4>Step 3: Get API Keys</h4>
                        <p>Go to **Project Settings {'>'} API**. You will need the <strong>Project URL</strong> and the <strong><code>anon</code> public key</strong>. You'll use these in the next step and for deployment.</p>

                        <h4>Step 4: Connect Frontend to Supabase</h4>
                        <p>First, install the Supabase client library:</p>
                        <CodeBlock>npm install @supabase/supabase-js</CodeBlock>
                        <p>Create a file (e.g., `src/services/supabaseClient.ts`) and add the following code. The `// TODO:` comments in the components show where you can now import and use this `supabase` client.</p>
                        <CodeBlock>{supabaseClientScript}</CodeBlock>
                    </Section>

                    <Section title="2. Payment Integration with Paddle">
                        <p>Paddle provides a complete payments infrastructure.</p>

                        <h4>Step 1: Setup Paddle</h4>
                        <ol>
                            <li>Create an account on <a href="https://paddle.com" target="_blank" rel="noopener noreferrer">Paddle</a>.</li>
                            <li>Go to **Catalog {'>'} Products** and create products for each course. Note the **Product ID** for each.</li>
                            <li>Go to **Developer Tools {'>'} Authentication** to get your **Vendor ID**.</li>
                        </ol>

                        <h4>Step 2: Integrate Paddle.js</h4>
                        <p>Add the Paddle.js script to your `index.html` head:</p>
                        <CodeBlock>{`<script src="https://cdn.paddle.com/paddle/js/paddle.js"></script>`}</CodeBlock>
                        
                        <p>Then, initialize Paddle in your `App.tsx` (or a similar top-level component) inside a `useEffect` hook. You'll set your Vendor ID as an environment variable later.</p>
                        <CodeBlock>{paddleEffectScript}</CodeBlock>

                        <h4>Step 3: Trigger Checkout</h4>
                        <p>In `CourseCard.tsx`, update the `handleBuyNow` function to use the Paddle product ID you stored in your Supabase `courses` table.</p>
                        <CodeBlock>{paddleCheckoutScript}</CodeBlock>
                    </Section>

                    <Section title="3. Deployment with Vercel">
                        <p>Vercel is a platform for frontend developers, providing an excellent deployment experience.</p>
                        
                        <h4>Step 1: Push to a Git Provider</h4>
                        <p>Make sure your project is a Git repository and pushed to GitHub, GitLab, or Bitbucket.</p>
                        
                        <h4>Step 2: Import Project on Vercel</h4>
                        <ol>
                            <li>Log in to <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">Vercel</a> with your Git provider account.</li>
                            <li>Click "Add New..." {'>'} "Project".</li>
                            <li>Import the Git repository for this project.</li>
                        </ol>
                        
                        <h4>Step 3: Configure Environment Variables</h4>
                        <p>In the Vercel project settings, go to **Settings {'>'} Environment Variables**. Add the keys from Supabase and Paddle. They **must be prefixed with `VITE_`** to be exposed to your frontend code.</p>
                        <ul>
                            <li><code>VITE_SUPABASE_URL</code>: Your Supabase Project URL.</li>
                            <li><code>VITE_SUPABASE_ANON_KEY</code>: Your Supabase `anon` public key.</li>
                            <li><code>VITE_PADDLE_VENDOR_ID</code>: Your Paddle Vendor ID.</li>
                        </ul>
                        <p>Your code (`supabaseClient.ts`, etc.) should already be set up to use these variables with `import.meta.env.VITE_...`</p>
                        
                        <h4>Step 4: Deploy</h4>
                        <p>Vercel will automatically detect the correct framework settings. Click "Deploy". Your site will be live in minutes!</p>
                    </Section>
                </div>
            </div>
        </section>
    );
};

export default BackendGuide;