import React from 'react';
import { isUsingDefaultCreds } from '../src/services/supabaseClient';

interface SetupGuideProps {
    error?: string;
}

const CodeBlock: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const textRef = React.useRef<HTMLPreElement>(null);
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        if (textRef.current) {
            navigator.clipboard.writeText(textRef.current.innerText);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    return (
        <div className="relative">
            <pre ref={textRef} className="bg-gray-800 text-white p-4 rounded-md overflow-x-auto text-sm">
                <code>{children}</code>
            </pre>
            <button
                onClick={handleCopy}
                className="absolute top-2 right-2 px-3 py-1 text-xs font-semibold rounded-md bg-gray-600 text-white hover:bg-gray-500"
            >
                {copied ? 'Copied!' : 'Copy'}
            </button>
        </div>
    );
};


const SetupGuide: React.FC<SetupGuideProps> = ({ error }) => {
    const dbSetupScript = `-- 1. Create the 'courses' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT,
  price NUMERIC,
  "imageUrl" TEXT,
  duration TEXT,
  paddle_product_id TEXT,
  file_url TEXT
);
ALTER TABLE public.courses DISABLE ROW LEVEL SECURITY;

-- 2. Insert mock data to populate the courses section
INSERT INTO public.courses (title, description, type, price, "imageUrl", duration, paddle_product_id)
VALUES
  ('Foundations of Mindfulness', 'A comprehensive video series teaching the core principles of mindfulness to reduce stress and cultivate presence.', 'Video Course', 49.99, 'https://picsum.photos/400/300?random=10', '4 Hours', 'prod_12345'),
  ('Morning Gratitude Meditation', 'Begin each day with a positive and grateful mindset through this beautifully guided audio meditation.', 'Audio Meditation', 9.99, 'https://picsum.photos/400/300?random=11', '15 Mins', 'prod_12346'),
  ('Chakra Balancing for Beginners', 'An introductory video course to understanding, clearing, and balancing your seven chakras for spiritual well-being.', 'Video Course', 69.99, 'https://picsum.photos/400/300?random=12', '6 Hours', 'prod_12347'),
  ('Deep Sleep Hypnosis', 'A soothing audio journey designed to help you release the day and drift into a deep, restorative, and peaceful sleep.', 'Audio Meditation', 14.99, 'https://picsum.photos/400/300?random=13', '30 Mins', 'prod_12348');

-- 3. Create the 'appointments' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL
);
ALTER TABLE public.appointments DISABLE ROW LEVEL SECURITY;

-- 4. Create the 'unavailabilities' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.unavailabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  unavailable_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  reason TEXT
);
ALTER TABLE public.unavailabilities DISABLE ROW LEVEL SECURITY;`;
    
    const storagePolicyScript = `DROP POLICY IF EXISTS "Authenticated users can manage course files" ON storage.objects;

CREATE POLICY "Authenticated users can manage course files"
ON storage.objects FOR ALL
TO authenticated
USING ( bucket_id = 'courses' );`;


    return (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/50 rounded-lg p-6 sm:p-8 my-8 text-text-primary dark:text-red-100">
            <h2 className="text-3xl font-serif font-bold text-red-700 dark:text-red-300 mb-4">Auralis Setup Required</h2>
            <p className="mb-6 text-red-600 dark:text-red-200">
                It looks like the application isn't connected to your database yet. Please follow the mandatory steps below to get everything working.
            </p>

            {error && (
                <div className="mb-6 bg-red-100 dark:bg-red-900/30 border border-red-300 dark:border-red-700 p-4 rounded-md">
                    <p className="font-bold text-red-800 dark:text-red-200">Detected Error:</p>
                    <p className="text-sm text-red-700 dark:text-red-300">{error}</p>
                </div>
            )}
            
            <div className="space-y-8">
                <div>
                    <h3 className="text-xl font-bold font-serif mb-2 text-primary dark:text-primary-light flex items-center gap-3">
                        <span className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground font-sans text-lg">1</span>
                        Connect to Your Supabase Project
                    </h3>
                    {isUsingDefaultCreds && (
                        <p className="text-amber-700 dark:text-amber-300 bg-amber-50 dark:bg-amber-900/30 p-3 rounded-md mb-4 border border-amber-200 dark:border-amber-800/50">
                            <b>Status:</b> You are currently using the default placeholder credentials.
                        </p>
                    )}
                    <ol className="list-decimal list-inside space-y-2 pl-4 text-text-secondary dark:text-text-primary">
                        <li>Go to your Supabase project dashboard at <a href="https://supabase.com/dashboard" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">supabase.com</a>.</li>
                        <li>Navigate to <b>Settings</b> (gear icon) &gt; <b>API</b>.</li>
                        <li>Copy your <b>Project URL</b> and `anon` <b>public</b> key.</li>
                        <li>Open the file <code className="text-sm bg-border-color p-1 rounded">src/services/supabaseClient.ts</code> in your editor.</li>
                        <li>Paste your unique credentials into the `supabaseUrl` and `supabaseAnonKey` variables, replacing the placeholders.</li>
                    </ol>
                </div>
                
                <div>
                    <h3 className="text-xl font-bold font-serif mb-2 text-primary dark:text-primary-light flex items-center gap-3">
                        <span className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground font-sans text-lg">2</span>
                        Set Up Database Tables
                    </h3>
                     <p className="mb-4 text-text-secondary dark:text-text-primary">In your Supabase dashboard, go to the <b>SQL Editor</b>, click <b>"+ New query"</b>, and run the script below to create all necessary tables and add sample data.</p>
                    <CodeBlock>{dbSetupScript}</CodeBlock>
                </div>

                <div>
                    <h3 className="text-xl font-bold font-serif mb-2 text-primary dark:text-primary-light flex items-center gap-3">
                        <span className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground font-sans text-lg">3</span>
                         Set Up File Storage
                    </h3>
                    <div className="space-y-4 text-text-secondary dark:text-text-primary">
                        <div>
                            <p><b>Part A: Create Storage Bucket</b></p>
                             <ol className="list-decimal list-inside space-y-1 pl-4">
                                <li>Go to the <b>Storage</b> section in your Supabase dashboard.</li>
                                <li>Click <b>"Create a new bucket"</b>.</li>
                                <li>Name the bucket exactly <code className="text-sm bg-border-color p-1 rounded">courses</code>.</li>
                                <li>Toggle <b>"Public bucket"</b> to ON.</li>
                                <li>Click <b>"Create bucket"</b>.</li>
                             </ol>
                        </div>
                        <div>
                             <p><b>Part B: Add Upload Policy</b></p>
                             <p className="mb-4">Go back to the <b>SQL Editor</b> and run this second script. This will fix file upload errors from the admin dashboard.</p>
                             <CodeBlock>{storagePolicyScript}</CodeBlock>
                        </div>
                    </div>
                </div>

                <div>
                    <h3 className="text-xl font-bold font-serif mb-2 text-primary dark:text-primary-light flex items-center gap-3">
                         <span className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground font-sans text-lg">4</span>
                        Refresh the Application
                    </h3>
                    <p className="mb-4 text-text-secondary dark:text-text-primary">Once you've completed all the steps above, do a hard refresh to load the application with your new configuration.</p>
                    <button
                        onClick={() => window.location.reload()}
                        className="px-6 py-3 font-semibold rounded-full bg-primary text-primary-foreground hover:bg-primary/90 transition-colors duration-300 shadow-md"
                    >
                        Refresh Application
                    </button>
                </div>
            </div>
        </div>
    );
};

export default SetupGuide;
